import React, { PropsWithChildren } from "react";
import classNames from "classnames";
import Head from "next/head";

import { Header } from "@components/Common/Header";
import { Scrolling } from "@components/Scrolling";

import styles from "./Layout.module.scss";

const siteTitle = "Tolistore";

export const LayoutComponent = React.forwardRef<
  HTMLDivElement,
  PropsWithChildren
>(({ children }, ref) => {
  const layoutClassName = classNames(styles.layout, "container");

  return (
    <div className={layoutClassName}>
      <Head>
        <title>{siteTitle}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main ref={ref}>
        <Scrolling vertical>{children}</Scrolling>
      </main>
    </div>
  );
});

LayoutComponent.displayName = "Layout";
